INSERT OR REPLACE INTO jobs (
  id, title, institution, country, city, research_area, language,
  description, apply_url, source_url, deadline, posted_at,
  employment_type, duration, tags_json, is_active, is_demo
) VALUES
  (
    'demo-job-001',
    'Postdoctoral Researcher in Machine Learning',
    'ResearchZeal Fictional AI Institute',
    'Germany',
    'Berlin',
    'Artificial Intelligence',
    'English/German',
    'Fictional demonstration vacancy for testing machine-learning job search. This is not a real position.',
    'https://example.com/apply/demo-job-001',
    'https://example.com/source/demo-job-001',
    date('now', '+30 days'),
    date('now', '-1 day'),
    'Full-time',
    '2 years',
    '["Machine Learning","Python"]',
    1,
    1
  ),
  (
    'demo-job-002',
    'Postdoctoral Fellow in Cancer Immunology',
    'Maple Demonstration Cancer Centre',
    'Canada',
    'Toronto',
    'Cancer Biology',
    'English/French',
    'Fictional demonstration vacancy for testing cancer-biology filters. This is not a real position.',
    'https://example.com/apply/demo-job-002',
    'https://example.com/source/demo-job-002',
    date('now', '+60 days'),
    date('now', '-2 days'),
    'Full-time',
    '3 years',
    '["Cancer Biology","Immunology"]',
    1,
    1
  ),
  (
    'demo-job-003',
    'Postdoctoral Scientist in Regional Climate Models',
    'Nordic Fictional Climate Laboratory',
    'Sweden',
    'Gothenburg',
    'Climate Science',
    'English/Swedish',
    'Fictional demonstration vacancy for testing climate-science searches. This is not a real position.',
    'https://example.com/apply/demo-job-003',
    'https://example.com/source/demo-job-003',
    date('now', '+90 days'),
    date('now', '-3 days'),
    'Full-time',
    '2 years',
    '["Climate Modelling","HPC"]',
    1,
    1
  ),
  (
    'demo-job-004',
    'Postdoctoral Fellow in Quantum Materials',
    'Sakura Demonstration Quantum College',
    'Japan',
    'Tsukuba',
    'Quantum Science',
    'English/Japanese',
    'Fictional demonstration vacancy for testing quantum-science listings. This is not a real position.',
    'https://example.com/apply/demo-job-004',
    'https://example.com/source/demo-job-004',
    NULL,
    date('now', '-4 days'),
    'Full-time',
    '24 months',
    '["Quantum Materials","Cryogenics"]',
    1,
    1
  ),
  (
    'demo-job-005',
    'Postdoctoral Researcher in Offshore Renewable Energy',
    'Lowlands Fictional Energy Institute',
    'Netherlands',
    'Delft',
    'Renewable Energy',
    'English/Dutch',
    'Fictional demonstration vacancy for testing renewable-energy results. This is not a real position.',
    'https://example.com/apply/demo-job-005',
    'https://example.com/source/demo-job-005',
    date('now', '+7 days'),
    date('now', '-5 days'),
    'Full-time',
    '2 years',
    '["Renewable Energy","Offshore Wind"]',
    1,
    1
  ),
  (
    'demo-job-006',
    'Postdoctoral Scientist in Neural Circuits',
    'Bohemian Demonstration Neuroscience Centre',
    'Czechia',
    'Prague',
    'Neuroscience',
    'English/Czech',
    'Fictional demonstration vacancy for testing neuroscience keyword matching. This is not a real position.',
    'https://example.com/apply/demo-job-006',
    'https://example.com/source/demo-job-006',
    date('now', '+45 days'),
    date('now', '-6 days'),
    'Full-time',
    '18 months',
    '["Neuroscience","Neural Circuits"]',
    1,
    1
  ),
  (
    'demo-job-007',
    'Postdoctoral Fellow in Adaptive Materials',
    'Southern Cross Fictional Materials Lab',
    'Australia',
    'Melbourne',
    'Materials Science',
    'English',
    'Fictional demonstration vacancy for testing materials-science filters. This is not a real position.',
    'https://example.com/apply/demo-job-007',
    'https://example.com/source/demo-job-007',
    date('now', '+20 days'),
    date('now', '-7 days'),
    'Full-time',
    '3 years',
    '["Materials Science","Adaptive Materials"]',
    1,
    1
  );
